### PR TITLE
user is always a string in this code

### PR DESCRIPTION
**Pull request by diclophis**

### CODE REVIEW

**Comment by diclophis** [comment]
Course, this means that we will start to see the real error `ArgumentError, "Invalid role .."`

**Comment by diclophis** [comment]
https://rpm.newrelic.com/accounts/4268/applications/217645798/filterable_errors#/show/02c85866-a4b7-11e9-94ce-0242ac110008_58873_65246/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart&filters=%5B%7B%22key%22%3A%22error.class%22%2C%22value%22%3A%22NoMethodError%22%2C%22like%22%3Afalse%7D%5D

**Comment by diclophis** [comment]
Screenshot_20190712_083408

**Review by bmidgley — APPROVED** [review]
Will it still raise but tell us what was wrong with the role list?

**Comment by diclophis** [comment]
yes, we should start to see the actual root error related i think to some role mismatch

**Pull request merged**
