### PR TITLE
there is no reason for this code to exist, its 100% dead

### PR DESCRIPTION
**Pull request by diclophis**
This is dead code

### CODE REVIEW

**Comment by bobby1190** [comment]
Do you think this is whats causing the segfault? It looks good to me

**Comment by id4ho** [comment]
image

**Comment by bobby1190** [comment]
Either way we are going to want to test it on this version of the gem to make sure our processes run fine to be safe

**Comment by diclophis** [comment]
Yes, my hunch is basically this.

1) hopefully this was the segfault
2) if not, hopefully this will keep segfaulting, but maybe the backtrace will lead us to our own tricky code in the bigmaven side that we can dig into

**Comment by jhmoore** [comment]
dead parrot

**Comment by racerpeter** [comment]
LGTM after we confirm it works by testing prod-alt. cc @salehrastani @aefhm

**Comment by diclophis** [comment]
@salehrastani / @aefhm if we could get this done sooner than later that would be great

**Review by salehrastani — APPROVED** [review]
LGTM it seems fine. But lets Dev QA this in the afternoon before merging into master

**Review by salehrastani — COMMENTED** [review]
LGTM, But lets Dev QA this in the afternoon before merging into master

**Review by salehrastani — CHANGES_REQUESTED** [review]
LGTM, But lets Dev QA this in the afternoon before merging into master.

Sorry for the confusing approvals above, but i didnt want this to sneak into master without dev QA

NOTE: Ive merged in the `aws_sdk_version` branch into this pr to include correct version aws-sdk gem.

**Review by aefhm — APPROVED** [review]

**Review by bobby1190 — APPROVED** [review]

**Review by salehrastani — DISMISSED** [review]

**Comment by salehrastani** [comment]
The bigmaven pull request related to this change is pointing gemfile to `remove-objectspace-enumeration` so we dont need to merge this into master.
https://github.com/mavenlink/mavenlink/pull/9152

**Comment by diclophis** [comment]
@salehrastani / @bobby1190 could we get this merged to master so we can close this PR?

**Comment by salehrastani** [comment]
@jon well have to merge this branch into the aws_sdk_version branch first and point Gemfile to aws_sdk_version on prod. Then merge this into master and delete branch, otherwise prod Gemfile is pointing to this branch and needs aws_sdk_version branch so it cant point directly to master. Ill do that.

**Comment by salehrastani** [comment]
I am merging this into aws_sdk_version. 

DO NOT DELETE THIS BRANCH UNTIL OUR GEMFILE POINTS BACK TO AWS_SDK_VERSION BRANCH!

**Pull request merged**
